### ISSUE TITLE
async methods should return a Promise

### ISSUE THREAD

**Issue by AMorgaut** [sysapps/tcp-udp-sockets#22] opened 2013-05-19 23:52 UTC
Mounir mentionned it in the last F2F Meeting, an intention in the Sysapps WG would be to implement Promise interfaces on the WG APIs
http://lists.w3.org/Archives/Public/public-sysapps/2013Apr/0129.html

This would mean that methods like close(), suspend(), resume(), joinMulticastGroup () leaveMulticastGroup(), halfClose(), and send() should defined a returning a Promise instead of being void functions.

We may have a look to the "Task Scheduler API" as an example of API using Future:
http://web-alarms.sysapps.org/

**Comment by marcoscaceres** [comment] 2013-05-20 09:49
I wouldn't copy from the messaging spec just yet. I've asked the DOM working group to review the text in the alarm spec to see if we are using futures correctly: http://lists.w3.org/Archives/Public/www-dom/2013AprJun/0121.html 

I haven't received a response yet, but I'll bug a few people to see if we get something.

**Comment by marcoscaceres** [comment] 2013-05-20 10:02
See also: https://github.com/sysapps/web-alarms/issues/29 

I just got a response from @annevk

**Comment by AMorgaut** [comment] 2013-05-20 13:28
I'm ok for not integrating it right now, but I thought it was important to create the issue to keep it in mind
And I'm not sure yet that the messaging API is the "best" example, so any other example like the Alarm spec should be mentioned in this thread to consider the best implementation.

A little detail, Messaging API has no link to the Future specification, while Web Alarm directly link to http://dom.spec.whatwg.org/#futures where I would have expected a dedicated line in the "Reference" section

I must say I've been a bit discouraged following the full discussions facing DOM Futures vs ES6 Promises:
- https://mail.mozilla.org/pipermail/es-discuss/2013-April/thread.html
- http://lists.w3.org/Archives/Public/public-script-coord/2013AprJun/

But I still think it is a worthy API move for asynchronous calls

**Comment by ClaesNilsson** [comment] 2013-06-27 15:18
The future interface is now reamed to promise, http://dom.spec.whatwg.org/#promises.

I see that SysApps API that previously used DOMRequest now use promises, which is natural. However, all methods, except send(), in the Raw Socket API are void functions and I am not sure on the benefit of using promises here. Any recent feedback from the WebApps WG?

**Comment by marcoscaceres** [comment] 2013-06-27 15:22
For idiomatic consistency, if a method is async, possibly takes an argument, and can result in either success or error, then it should use a promise.

**Comment by marcoscaceres** [comment] 2013-06-27 15:23
@ClaesNilsson the discussion that took place in the telephony API around this might be of help (see the comments in the last few days): 

https://github.com/sysapps/telephony/issues/17

**Comment by marcoscaceres** [comment] 2013-06-27 15:25
(updated the description of this bug to talk about Promises instead of Futures)

**Comment by sicking** [comment] 2013-07-03 05:15
The question is, are functions like close(), suspend() and resume() really async?

If you call close(), the behavior of the API immediately changes in that you won't receive any more messages. So from an author point of view the function is synchronous.

Same thing with suspend(), it will immediately prevent any more messages from getting delivered.

And at what point can we say that resume() succeeded or failed? Is it useful to indicate a failed resume in any other way that through the normal mechanism of "connection lost"? If not, it doesn't seem useful to return a promise.

halfClose() also seems like it will immediately change the behavior in that it immediately prevents the author from sending more data.

I don't understand enough about joinMulticastGroup and leaveMulticastGroup to have an opinion here. But the fact that the API currently doesn't asynchronously deliver a result of any kind makes me think that it's not appropriate to use promises here.

send() is the only function that I can see potentially having a useful asynchronous result. Once the TCP packets that the data generate has been successfully acknowledged by the receiver could we provide a "success" callback through a promise object. However I don't think this is something TCP APIs usually provide, is it? I'm worried that implementing this would be a big burden on the API implementation. Possibly even with performance implications.

Alternatively send() could generate a success callback once the data has been sent successfully handed to the TCP stack on the platform. However I'm wondering what the use case is for this. Again, from the author point of view, the data has been successfully handed to the TCP stack as soon as send() returns.

It'd be good to know what other APIs provide in this space.

**Comment by ClaesNilsson** [comment] 2013-08-14 08:21
I agree with Jonas that the methods close(), halfclose(), suspend() and resume()  are synchronous in their nature and not applicable for returning a promise object.

For joinMulticast()  and leaveMulticast() I have looked at other APIs and most of them are synchronous. However, this one provides a confirmation when join group is completeted but I don’t find any error handling if join group fails: http://msdn.microsoft.com/library/windowsphone/develop/hh286407(v=vs.105).aspx.  

Calling joinMulticast()  means that an Internet Group Management Protocol (IGMP) packet to the router requesting membership to the multicast group is sent. Looking at http://www.networksorcery.com/enp/protocol/igmp.htm there is a reply a reply message, in which the Code field specifies the outcome of the request. I am not yet 100% sure but I may have to change joinMulticast()  and leaveMulticast()  to asynchronous methods using promises. Maybe 4D has some feedback? Under all circumstances the specification should be completed with stepwise descriptions of these methods including error handling (for example the situation when the given multicastGroupAddress is out the reserved multicast address range is 224.0.0.0 to 239.255.255.255 should throw an exception).

Looking at send () I compare with the Node.js socket.write method that has an optional callback that will be executed “when the data is finally written out - this may not be immediately”, http://nodejs.org/api/net.html#net_socket_write_data_encoding_callback. Moreover there is a Boolean returned stating the state of the send buffer similar to what we have in the SysApps API.  I am not clear on the use cases for using the optional callback and when it actually is executed. What is exactly meant by “finally written out”. Confirmed by the server? I don’t think that the API we are designing should have to wait for server confirmation before the application can send the data packet as this would have severe performance issues.

So I think that the current design of the send() method is ok. The only motivation for changing to promises would be to achieve a syntax consistent with other APIs but it would not add any specific benefits in functionality of the API. If we change to promises we should replace the Boolean return value, which is a hint to the caller that they may either continue sending more data immediately, or should want to wait until the transport layer has transmitted buffered data that already have been written to the socket before buffering more, with a Boolean value of the resolver's internal fulfill algorithm. I assume that the fulfill algorithm should be called immediately when the data to send has been successfully delivered to the underlying protocol layer. Error handling for send buffer full or because there is some error in the underlying protocol could be handled through the resolver's internal reject algorithm.

A stepwise description for TCPSocket send() based on promises could be:
1.  If readyState is not "open" throw DOMException InvalidStateError and abort these steps.
2.  If the internal "IgnoreAllSendCalls" flag is set then abort these steps.
3.  Let promise be a new Promise object and resolver its associated resolver.
4.  Return promise and run the remaining steps asynchronously.
5.  If the data cannot be sent, e.g. because it would need to be buffered but the buffer is full or because there is some error in the underlying protocol, the user agent must set an internal "IgnoreAllSendCalls" flag and execute the following substeps and then abort the remaining steps:
    1.  Change the readyState attribute's value to "closed".
    2.  Let socketerror be a new SocketErrorEvent.
    3.  Set socketerror.name  to "NetworkError".
    4.  Set the socketerror.type to the appropriate error type. See enum SocketErrorType.
    5.  Set the socketerror.message to an informative message stating the reason for the error.
    6.  Run resolver's internal reject algorithm with socketerror as value.
    7.  queue a task that changes the readyState attribute's value to "closed" and fire an event named close at the
        TCPSocket object.
6. Make a request to the system to send TCP data with data passed in the data parameter to the address and port of the recipient as stated by the TCPSocket object constructor's remoteAddress and remotePort fields.
7.  When the request has been completed run the following substeps:
    1.  Let result be a Boolean value.
    2.  Set result to true or false as a hint to the caller that they may either continue sending more data immediately, or should want to wait until the transport layer has transmitted buffered data that already have been written to the socket before buffering more. When less than an implementation specific value has been buffered and it's safe to immediately write more set result to true. When more than an implementation specific value has been buffered set result to false. This means that the caller should wait before buffering more data by more calls to send until the ondrain event handler has been called.
    3.  Run resolver's internal fulfill algorithm with result as value.
8.  Any invocation of this method that does not throw an exception or runs the promise resolver’s reject alorithm must increase the bufferedAmount attribute.
-   If the send data argument is DOMString the bufferedAmount attribute is increased by the number of bytes needed to express the argument as UTF-8. [UNICODE] [UTF-8]
-   If the send data argument is Blob the bufferedAmount attribute is increased by the size of the Blob object's raw data, in bytes. [FILE-API]
-   If the send data argument is ArrayBuffer the bufferedAmount attribute is increased by the length of the ArrayBuffer in bytes. [TYPED-ARRAYS]
-   If the send data argument is ArrayBufferView the bufferedAmount attribute is increased by the length of the ArrayBufferView in bytes. [TYPED-ARRAYS]

**Comment by anotherlin** [comment] 2013-08-18 23:03
Synchronous or not asynchronous functions is an API design decision rather than depending on the actual "nature" of operation : For a TCP socket, the Berkeley socket's close() is "synchronous" because you are not allowed to read, write or do anything with the socket after its call. But an actual TCP termination requires both peers exchanging FIN packets and their acknowledgement ACK packets. So a TCP socket is really "closed" after that, which can take some time.

For the multicast, I've checked your link (http://www.networksorcery.com/enp/protocol/igmp.htm). The possible reply is in RFC988 which is obsolete (1986!). I've taken a quick look at IGMPv1's and IGMPv2's RFCs (1112 and 2236). There is no reply for "join". It's just the "report" (that I'm in multicast group) packet which makes the "join" operation. So packet can actually be lost, and RFC suggest to send the report packet twice at short interval during join. Until today, I've never taken a look at the actual RFCs, I've always been told that the function were synchronous, and I've never run into problem with join/leave multicast. I'd rather think we should leave this as synchronous.

NodeJS's write() features are really good in my opinion. Basically, when you do a send() on Berkeley socket, you are just queuing bytes into the socket's (kernel side) write buffer. For instance, on Linux, default size is defined at : /proc/sys/net/core/wmem_default, and is around 200k on my system. write() will return true if the entire data has been queued in the socket's write buffer, or false if can contain only part or none of it. In which case, NodeJS takes care to buffer the data into user memory. The optional callback will be called when the data in submitted in the write buffer is actually written on the network. The documentation is not very precise, but I don't think they mean "when the ACK for this part of data has been received from peer". Anyway, the callback is optional and you don't have to wait for it before you can send more data, so it doesn't have negative impact on performance.

**Comment by ClaesNilsson** [comment] 2013-08-19 08:17
Thanks Ke-Fong. This helps a lot.

So, the proposal is to keep joinMulticast() and leaveMulticast() as synchronous functions.

For send() I think that the current design fulfills what we need. I am not clear on the use cases for the optional callback in NodeJS's write() feature. If we have use cases for providing a callback to the application when the data in  in the write buffer is actually written on the network we could change the send() method to a promised based method. I don't really see any use cases for this so I think that we should keep the current design. Any other opinions?

**Comment by anotherlin** [comment] 2013-08-19 14:06
A possible use case for the optional callback : sending a large file to a peer. Initiate sending by calling write() with a chunk of let's say 16k. Each time the callback is serviced, call (inside the callback) write() with more 16k data and same callback until the file is fully transferred. The callback is triggered only when the buffer has been written (flushed) on the network, hence you're certain that further data will be buffered in kernel's socket write buffer and not in user memory managed by Node. This is a very efficient way to send that does automatic flow control of the sending.

**Comment by ClaesNilsson** [comment] 2013-08-20 08:13
Ok, thanks Ke-Fong. In our RawSocket API send() method we have a boolean return value similar to what node.js write() has. So in this aspect the semantics in these two methods is similar. However, if we want to achieve a design in our send() method with promises that supports both the boolean and the optional callback I see a problem. In the potential promised based flow I describe above I state that the resolver's internal fulfill algorithm (with the boolean as value) is run immediately to state if it is possible to buffer more data or not. The criteria for the callback is different, i.e. it is called when the data has been sent out on the network. Does anyone know if it is possible to create a design with promises that basically has two fulfill callbacks issued based on different criteria? Can a resolve callback be used?
Of course we could just copy the node.js write() design but then we don't get a promised based design.

**Comment by anotherlin** [comment] 2013-08-21 15:17
I think we should leave our send() the way it is. We actually have an "ondrain" event (all buffered data from send() calls have been written to network) which has same purpose as NodeJS's optional write() callback.

NodeJS is just a little bit more elaborate in that it distinguish user memory (NodeJS's drain event) vs. kernel memory (optional callback). I don't think it is needed to go to that much detail.

**Comment by ClaesNilsson** [comment] 2013-08-22 08:22
I agree.

2013/8/21 Lin Ke-Fong notifications@github.com

**Comment by marcoscaceres** [comment] 2013-08-26 15:43
I don't think this is a good idea:

```
1. If readyState is not "open" throw DOMException InvalidStateError and abort these steps.
2. If the internal "IgnoreAllSendCalls" flag is set then abort these steps.
```

Exceptions should not be thrown in APIs using promises - the error resolver should be called instead. In 2, it's going to confuse people if nothing happens, right? That should result in an error.

**Comment by ClaesNilsson** [comment] 2013-08-26 18:33
The proposal was to keep the method as it is and not redesign it to use promises as that would give no benefits.

The design with the "IgnoreAllSendCalls" flag is based on a suggestion from Jonas. See the end of http://lists.w3.org/Archives/Public/public-sysapps/2013Jul/0020.html. However, this could maybe be done more elegant? So maybe a promised based design would be better after all and we may need the flag?

If we keep the semantics of the method but changes to a promised based syntax could it be something like:
1. Let promise be a new Promise object and resolver its associated resolver.
2. Return promise and run the remaining steps asynchronously.
3. If the data cannot be sent, e.g. because the socket is not open, he data would need to be buffered but the buffer is full or because there is some error in the underlying protocol, the user agent must execute the following substeps and then abort the remaining steps:
   1. Change the readyState attribute's value to "closed".
   2. Let socketerror be a new SocketErrorEvent.
   3. Set socketerror.name to "NetworkError".
   4. Set the socketerror.type to the appropriate error type. See enum  
      SocketErrorType.
   5. Set the socketerror.message to an informative message stating the reason 
      for the error.
   6. Run resolver's internal reject algorithm with socketerror as value.
   7. queue a task that changes the readyState attribute's value to "closed" and 
      fire an event named close at theTCPSocket object.
4. Make a request to the system to send TCP data with data passed in the data parameter to the address and port of the recipient as stated by the TCPSocket object constructor's remoteAddress and remotePort fields.
5. When the request has been completed run the following substeps:
   1. Let result be a Boolean value.
   2. Set result to true or false as a hint to the caller that they may either continue sending more data immediately, or should want to wait until the transport layer has transmitted buffered data that already have been written to the socket before buffering more. When less than an implementation specific value has been buffered and it's safe to immediately write more set result to true. When more than an implementation specific value has been buffered set result to false. This means that the caller should wait before buffering more data by more calls to send until the ondrain event handler has been called.
   3. Run resolver's internal fulfill algorithm with result as value.
6. Any invocation of this method that does not throw an exception or runs the promise resolver’s reject alorithm must increase the bufferedAmount attribute.
- If the send data argument is DOMString the bufferedAmount attribute is increased by the number of bytes needed to express the argument as UTF-8. [UNICODE] [UTF-8]
- If the send data argument is Blob the bufferedAmount attribute is increased by the size of the Blob object's raw data, in bytes. [FILE-API]
- If the send data argument is ArrayBuffer the bufferedAmount attribute is increased by the length of the ArrayBuffer in bytes. [TYPED-ARRAYS]
- If the send data argument is ArrayBufferView the bufferedAmount attribute is increased by the length of the ArrayBufferView in bytes. [TYPED-ARRAYS]

WDYT?

**Comment by draggett** [comment] 2013-08-29 17:48
Who are the target users for the raw socket API?  My expectation is that people wanting to use raw sockets will be system programmers familiar with the principles of UDP and TCP/IP, and the POSIX sockets interface. I anticipate the development of libraries using raw sockets to implement specific protocols and for specific use cases.  A higher level sockets API could make it harder for library developers to do a good job.

One example is whether we should expose EWOULDBLOCK which allows you to determine when a call to send will need to block. The Node.js socket.write method doesn't appear to expose this feature, and instead supports a call back when a synchronous send completes. It would be good to contact the developers of the Node net module to get their perspective and their rationale for their API with respect to POSIX sockets.

Some specific cases to look at include sending very large amounts of data, and trying to send at a constant rate, where the app needs to adjust this rate depending upon  a means to estimate the effective bandwidth of a connection. We should consider providing example code for these cases.

**Comment by ClaesNilsson** [comment] 2013-08-29 18:41
This issue is about using promises and the conclusion at the Toronto Raw Socket small group session is that a promised based syntax of the send() method is possible without changing the semantics of the method.

Dave's comment above is more relevant for https://github.com/sysapps/raw-sockets/issues/46 so I copy Dave's comment to 46 and close this one (22)

**Closed as completed by ClaesNilsson** 2013-08-29 18:41 UTC
