### ISSUE TITLE
These are not the raw sockets you are looking for

### ISSUE THREAD

**Issue by annevk** [sysapps/tcp-udp-sockets#58] opened 2013-11-11 09:16 UTC
@mnot mentioned to me that what you are defining here is a socket API. Raw sockets are something else. See http://sock-raw.org/papers/sock_raw

**Comment by marcoscaceres** [comment] 2013-11-11 10:28
Duplicate of: https://github.com/sysapps/raw-sockets/issues/42 ?

**Comment by annevk** [comment] 2013-11-12 07:18
Yeah seems like it.

**Closed as completed** 2013-11-12 08:10 UTC
